/*
 * DIO_config.h
 *
 *  Created on: Jul 5, 2022
 *      Author: Shimaa Ismail
 */

#ifndef MCAL_DIO_DIO_CONFIG_H_
#define MCAL_DIO_DIO_CONFIG_H_
/*
 * CHOOSE DIRECTION INPUT OR OUTPUT
 */


#define PA0_DIR       PIN_DIRECTION_OUTPUT
#define PA1_DIR       PIN_DIRECTION_OUTPUT
#define PA2_DIR       PIN_DIRECTION_OUTPUT
#define PA3_DIR       PIN_DIRECTION_OUTPUT
#define PA4_DIR       PIN_DIRECTION_OUTPUT
#define PA5_DIR       PIN_DIRECTION_OUTPUT
#define PA6_DIR       PIN_DIRECTION_OUTPUT
#define PA7_DIR       PIN_DIRECTION_OUTPUT

#define PB0_DIR       PIN_DIRECTION_OUTPUT
#define PB1_DIR       PIN_DIRECTION_OUTPUT
#define PB2_DIR       PIN_DIRECTION_OUTPUT
#define PB3_DIR       PIN_DIRECTION_OUTPUT
#define PB4_DIR       PIN_DIRECTION_OUTPUT
#define PB5_DIR       PIN_DIRECTION_OUTPUT
#define PB6_DIR       PIN_DIRECTION_OUTPUT
#define PB7_DIR       PIN_DIRECTION_OUTPUT

#define PC0_DIR       PIN_DIRECTION_OUTPUT
#define PC1_DIR       PIN_DIRECTION_OUTPUT
#define PC2_DIR       PIN_DIRECTION_OUTPUT
#define PC3_DIR       PIN_DIRECTION_OUTPUT
#define PC4_DIR       PIN_DIRECTION_OUTPUT
#define PC5_DIR       PIN_DIRECTION_OUTPUT
#define PC6_DIR       PIN_DIRECTION_OUTPUT
#define PC7_DIR       PIN_DIRECTION_OUTPUT

#define PD0_DIR       PIN_DIRECTION_OUTPUT
#define PD1_DIR       PIN_DIRECTION_OUTPUT
#define PD2_DIR       PIN_DIRECTION_OUTPUT
#define PD3_DIR       PIN_DIRECTION_OUTPUT
#define PD4_DIR       PIN_DIRECTION_OUTPUT
#define PD5_DIR       PIN_DIRECTION_OUTPUT
#define PD6_DIR       PIN_DIRECTION_OUTPUT
#define PD7_DIR       PIN_DIRECTION_OUTPUT




#endif /* MCAL_DIO_DIO_CONFIG_H_ */
